-- AlterTable
ALTER TABLE "ItemSubPenganggaran" ALTER COLUMN "target" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "progres" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Penganggaran" ALTER COLUMN "target" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "progres" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Perencanaan" ALTER COLUMN "target" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "progres" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "SubPenganggaran" ALTER COLUMN "target" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "progres" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "SubPerencanaan" ALTER COLUMN "target" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "progres" SET DATA TYPE DECIMAL(65,30);
